name: expensync
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.11
  connectivity_plus: ^6.0.3
  drift: ^2.18.0
  drift_dev: ^2.18.0
  electricsql: ^0.8.1
  electricsql_cli: ^0.8.1
  electricsql_flutter: ^0.8.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3: ^2.4.4
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
